name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw64/mingw-w64-x86_64-qt5-static
            mingw-w64-x86_64-zlib       # Added zlib
            mingw-w64-x86_64-pcre       # Added PCRE for qtpcre2
      - name: preCheck
        shell: msys2 {0}
        run: |
          ls /mingw64/lib | grep Qt5   # For Qt libraries
          ls /mingw64/lib | grep zlib  # For zlib
      - name: build
        shell: msys2 {0}
        run: |
          ln -s $(pwd) ~/NxNandManager
          cd ~/NxNandManager/NxNandManager/gui
          /mingw64/qt5-static/bin/qmake.exe NxNandManager.pro 'CONFIG += STATIC ARCH64'
          make -j"$(nproc)" VERBOSE=1
          mkdir -p $GITHUB_WORKSPACE/bin
          cp release/NxNandManager.exe $GITHUB_WORKSPACE/bin
          cp ../virtual_fs/dokan/x64/dokan1.dll $GITHUB_WORKSPACE/bin
      - uses: actions/upload-artifact@v3
        with:
          name: NxNandManager
          path: bin/*
